print(f"Division: {10/10}\n")
print(f"Division: {10/8}\n")
print(f"Division: {10/6}\n")
print(f"Division: {10/4}\n")
print(f"Division: {10/2}\n")
print(f"Division: {10/0}\n")    # Division by zero!
print(f"Division: {10/1}\n")
print(f"Division: {10/3}\n")
print(f"Division: {10/5}\n")
print(f"Division: {10/7}\n")
